  spring :
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
     # url: jdbc:mysql://127.0.0.1:3306/testschema?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
      url: jdbc:mysql://localhost:3306/testschema?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
      username: root
      password : corud

    jpa :
      hibernate:
        ddl-auto: create
        #ddl-auto: update
      properties:
        hibernate:
          format_sql: true

    output:
      ansi:
        enabled: always


    jackson:
      property-naming-strategy: SNAKE_CASE

  logging.level:
    org.hibernate.SQL: debug
    org.apche.coyote.http11: debug
    org.hibernate.type: trace
